apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: realtime-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
